fix: terraform code matching

diff --git a/.github/workflows/terraform_plan.yml b/.github/workflows/terraform_plan.yml
--- a/.github/workflows/terraform_plan.yml
+++ b/.github/workflows/terraform_plan.yml
@@ -37,10 +37,17 @@ jobs:
         id: plan
         run: |
           terraform plan -no-color -detailed-exitcode | tee terraform/plan_full.txt
+          exit_code=$?
           
           summary=$(grep -E "(Plan:|module\.)" terraform/plan_full.txt | head -n 20 | sed ':a;N;$!ba;s/\n/\\n/g')
           echo "summary_output=$summary" >> $GITHUB_OUTPUT
-
+          
+          if [ $exit_code -eq 1 ]; then
+            echo "Terraform plan failed with errors."
+            exit 1
+          fi
+          
+          exit 0
         working-directory: ./terraform
 
       - name: Upload full plan as artifact
